"""presentation generation settings

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-23 20:51:15.363033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presentations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audience', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tone', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presentations', schema=None) as batch_op:
        batch_op.drop_column('language')
        batch_op.drop_column('tone')
        batch_op.drop_column('audience')

    # ### end Alembic commands ###
